apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      volumes:
      - name: host-path
        hostPath:
          path: /hostPath
      containers:
      - image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123"
        name: mysql
        resources: {}
        volumeMounts:
        - name: host-path
          mountPath: /hostPath
status: {}
